import { access, constants } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { PlayableSource } from '../player/transport.js';
import type { Track } from '../player/track.js';

/**
 * The bundled synthetic audio.
 *
 * These are smoke-test assets, not music: pure sine sequences generated by
 * FFmpeg (see `tools/generate-local-assets.ts`) so queue, auto-next and FIFO
 * can be verified by ear without any copyrighted material or external
 * provider. `notes`/`noteSeconds` are the generator's recipe - they never
 * reach a `Track`.
 */
export interface LocalAsset {
  readonly id: string;
  readonly title: string;
  readonly fileName: string;
  readonly durationMs: number;
  /** Sine frequencies in Hz, played in order. */
  readonly notes: readonly number[];
  readonly noteSeconds: number;
}

function asset(
  id: string,
  title: string,
  notes: readonly number[],
  noteSeconds: number,
): LocalAsset {
  return {
    id,
    title,
    fileName: `${id}.opus`,
    durationMs: Math.round(notes.length * noteSeconds * 1000),
    notes,
    noteSeconds,
  };
}

export const LOCAL_ASSETS: readonly LocalAsset[] = [
  asset('arpeggio', 'Test tone: arpeggio', [440, 554, 659, 880], 2),
  asset('ascending', 'Test tone: ascending scale', [262, 294, 330, 349, 392, 440, 494, 523], 0.75),
  asset(
    'descending',
    'Test tone: descending scale',
    [523, 494, 440, 392, 349, 330, 294, 262],
    0.75,
  ),
];

export const DEFAULT_LOCAL_ASSET_ID = 'arpeggio';

// `<repo>/src/audio` with tsx, `<repo>/dist/audio` once built: both are two
// levels below the repository root.
const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

export const ASSETS_DIR = resolve(packageRoot, 'assets');

export function findLocalAsset(id: string): LocalAsset | undefined {
  return LOCAL_ASSETS.find((candidate) => candidate.id === id);
}

export function localAssetPath(asset: LocalAsset): string {
  return resolve(ASSETS_DIR, asset.fileName);
}

/**
 * Resolves a local track into something FFmpeg can read.
 *
 * This is the milestone 3 stand-in for the future provider resolver: the
 * player only ever sees `Track -> PlayableSource`.
 */
export async function resolveLocalTrack(track: Track): Promise<PlayableSource> {
  // Only local tracks exist today; a future provider resolver will dispatch on
  // `track.source` before ever reaching this one.
  const asset = findLocalAsset(track.sourceId);
  if (asset === undefined) {
    throw new Error(`Unknown local asset: ${track.sourceId}`);
  }

  const path = localAssetPath(asset);
  await assertAssetExists(path);
  return { kind: 'file', input: path };
}

/**
 * Fails with an actionable message when an asset is missing, instead of
 * letting FFmpeg die on an unreadable input.
 */
export async function assertAssetExists(path: string): Promise<void> {
  try {
    await access(path, constants.R_OK);
  } catch (error) {
    throw new Error(
      `The audio asset is missing or unreadable (${path}). Run "npm run assets:generate" to regenerate it.`,
      { cause: error },
    );
  }
}
