import { access, constants } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Synthetic audio used by `/playlocal` to smoke test the voice pipeline.
 *
 * The asset is generated by `npm run assets:tone` (see `tools/generate-test-tone.ts`)
 * and contains nothing but computer generated sine tones - no copyrighted
 * material is involved. It exists only to prove that
 * FFmpeg -> AudioPlayer -> Discord actually carries sound.
 */
export const TEST_TONE_FILE = 'test-tone.opus';

/** Human readable description used in the `/playlocal` answer. */
export const TEST_TONE_DESCRIPTION = 'synthetic test tone (A-C#-E-A arpeggio, ~8s)';

// `<repo>/src/audio` when running with tsx, `<repo>/dist/audio` once built:
// both are two levels below the repository root.
const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');

export const TEST_TONE_PATH = resolve(packageRoot, 'assets', TEST_TONE_FILE);

/**
 * Fails fast with an actionable message when the asset is missing, instead of
 * letting FFmpeg die on an unreadable input.
 */
export async function assertTestToneExists(path: string = TEST_TONE_PATH): Promise<void> {
  try {
    await access(path, constants.R_OK);
  } catch (error) {
    throw new Error(
      `The test tone asset is missing or unreadable (${path}). Run "npm run assets:tone" to regenerate it.`,
      { cause: error },
    );
  }
}
